# ===============================
# [ Spring Properties ]
# ===============================
spring:
  activemq.broker-url: tcp://localhost:61616
  activemq.user: admin
  activemq.password: admin
  datasource:
    url: jdbc:postgresql://localhost:5433/javamastery?user=javamastery&password=javamastery
  mustache:
    expose-request-attributes: true
    suffix: .html

logging:
  level:
    com:
      github:
        greatlirik:
          DEBUG
    org:
      springframework: INFO
      hibernate: ERROR

management.endpoints.web.exposure.include: health,info,env,beans,mappings,loggers

